apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apiextensions.k8s.io/v1beta1","kind":"CustomResourceDefinition","metadata":{"annotations":{},"name":"sealedsecrets.bitnami.com"},"spec":{"group":"bitnami.com","names":{"kind":"SealedSecret","listKind":"SealedSecretList","plural":"sealedsecrets","singular":"sealedsecret"},"scope":"Namespaced","version":"v1alpha1"}}
  creationTimestamp: "2019-11-21T10:33:18Z"
  generation: 1
  name: sealedsecrets.bitnami.com
  resourceVersion: "384898742"
  uid: 556bb0dc-0c4a-11ea-a348-06d51f7991b4
spec:
  conversion:
    strategy: None
  group: bitnami.com
  names:
    kind: SealedSecret
    listKind: SealedSecretList
    plural: sealedsecrets
    singular: sealedsecret
  preserveUnknownFields: true
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
status:
  acceptedNames:
    kind: SealedSecret
    listKind: SealedSecretList
    plural: sealedsecrets
    singular: sealedsecret
  conditions:
  - lastTransitionTime: "2019-11-21T10:33:18Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: null
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  - lastTransitionTime: "2022-07-20T15:07:40Z"
    message: 'spec.preserveUnknownFields: Invalid value: true: must be false'
    reason: Violations
    status: "True"
    type: NonStructuralSchema
  storedVersions:
  - v1alpha1
