apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"name":"nginx-ingress-role","namespace":"dinopark-test"},"rules":[{"apiGroups":[""],"resources":["configmaps","pods","secrets","namespaces","services","endpoints"],"verbs":["get","list","watch"]},{"apiGroups":[""],"resourceNames":["ingress-controller-leader-nginx-dinopark-test"],"resources":["configmaps"],"verbs":["get","update"]},{"apiGroups":[""],"resources":["configmaps","events"],"verbs":["create"]},{"apiGroups":["extensions"],"resources":["ingresses"],"verbs":["list","watch"]}]}
  creationTimestamp: "2019-05-23T08:12:47Z"
  name: nginx-ingress-role
  namespace: dinopark-test
  resourceVersion: "520831326"
  uid: 8ccc6e3d-7d32-11e9-976f-06f807dee916
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - secrets
  - namespaces
  - services
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resourceNames:
  - ingress-controller-leader-nginx-dinopark-test
  resources:
  - configmaps
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  verbs:
  - create
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - list
  - watch
