apiVersion: batch/v1
kind: CronJob
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1beta1","kind":"CronJob","metadata":{"annotations":{},"name":"dino-park-packs-notify-cron","namespace":"dinopark-dev"},"spec":{"jobTemplate":{"spec":{"template":{"spec":{"containers":[{"args":["/bin/sh","-c","curl -X POST dino-park-packs-service/internal/notify/all"],"image":"curlimages/curl","name":"dino-park-packs-notify-cron"}],"restartPolicy":"OnFailure"}}}},"schedule":"0 12 * * * "}}
  creationTimestamp: "2020-06-15T11:38:38Z"
  name: dino-park-packs-notify-cron
  namespace: dinopark-dev
  resourceVersion: "475553031"
  uid: d953831e-352c-4877-b50c-ce5b7b1e4062
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - /bin/sh
            - -c
            - curl -X POST dino-park-packs-service/internal/notify/all
            image: curlimages/curl
            imagePullPolicy: Always
            name: dino-park-packs-notify-cron
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '0 12 * * * '
  successfulJobsHistoryLimit: 3
  suspend: false
