apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-exporter-conf
  namespace: monitoring
data:
  config.yml: |-
    region: us-west-2
    metrics:
      - aws_namespace: AWS/ELB
        aws_metric_name: SurgeQueueLength
        aws_dimensions: [LoadBalancerName]
        aws_dimension_select:
          LoadBalancerName: [a00435690f99111e8989b0ace417809a, af3ef016b807c11e9976f06f807dee91]
        aws_statistics: [Sum, Average, SampleCount, Maximum]

      - aws_namespace: AWS/ES
        aws_metric_name: SearchRate
        aws_dimensions: [DomainName, ClientId]
        aws_statistics: [Average]

