apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-exporter-conf
  namespace: monitoring
data:
  config.yml: |-
    region: us-west-2
    metrics:
      - aws_namespace: AWS/ELB
        aws_metric_name: SurgeQueueLength
        aws_dimensions: [LoadBalancerName]
        aws_dimension_select:
          LoadBalancerName: [a00435690f99111e8989b0ace417809a]
        aws_statistics: [Sum, Average, SampleCount, Maximum]

