apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1beta1","kind":"Role","metadata":{"annotations":{},"name":"nginx-ingress-role","namespace":"monitoring"},"rules":[{"apiGroups":[""],"resources":["configmaps","pods","secrets","namespaces","services","endpoints"],"verbs":["get","list","watch"]},{"apiGroups":[""],"resourceNames":["ingress-controller-leader-nginx-monitoring"],"resources":["configmaps"],"verbs":["get","update"]},{"apiGroups":[""],"resources":["configmaps","events"],"verbs":["create"]},{"apiGroups":["extensions"],"resources":["ingresses"],"verbs":["list","watch"]}]}
  creationTimestamp: "2019-05-20T12:41:12Z"
  name: nginx-ingress-role
  namespace: monitoring
  resourceVersion: "34938919"
  uid: 8c947623-7afc-11e9-be09-0a6aa30f6294
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - secrets
  - namespaces
  - services
  - endpoints
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resourceNames:
  - ingress-controller-leader-nginx-monitoring
  resources:
  - configmaps
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  verbs:
  - create
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - list
  - watch
