apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: graylog-master
  namespace: logging
spec:
  selector:
    matchLabels:
      k8s-app: graylog-master
  serviceName: "graylog-master"
  replicas: 1
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::320464205386:role/graylog-role-prod-us-west-2
      labels:
        k8s-app: graylog-master
        graylog-role: master
        graylog: "true"
    spec:
      terminationGracePeriodSeconds: 70
      affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: graylog-role
                  operator: In
                  values:
                  - graylog-slave
              topologyKey: kubernetes.io/hostname
      containers:
        - name: graylog-master
          image: graylog/graylog:3.0.2
          env:
          - name: GRAYLOG_PASSWORD_SECRET
            valueFrom:
              secretKeyRef:
                name: graylog-config-secret
                key: admin_pw
          - name: GRAYLOG_ROOT_PASSWORD_SHA2
            valueFrom:
              secretKeyRef:
                name: graylog-config-secret
                key: admin_pw_sha2
          - name: GRAYLOG_MONGODB_URI
            valueFrom:
              configMapKeyRef:
                name: graylog-master-config
                key:  mongodb_uri
          - name: GRAYLOG_IS_MASTER
            valueFrom:
              configMapKeyRef:
                name: graylog-master-config
                key:  is_master
          - name: GRAYLOG_ELASTICSEARCH_HOSTS
            valueFrom:
              configMapKeyRef:
                name: graylog-master-config
                key:  elasticsearch_hosts
          - name: GRAYLOG_HTTP_BIND_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: graylog-master-config
                key: http_bind_address
          - name: GRAYLOG_HTTP_PUBLISH_URI
            valueFrom:
              configMapKeyRef:
                name: graylog-master-config
                key: http_publish_uri
          - name: GRAYLOG_HTTP_EXTERNAL_URI
            valueFrom:
              configMapKeyRef:
                name: graylog-master-config
                key: http_external_uri
          - name: GRAYLOG_SERVER_JAVA_OPTS
            valueFrom:
              configMapKeyRef:
                name: graylog-master-config
                key: server_java_opts
          - name: GRAYLOG_TRUSTED_PROXIES
            valueFrom:
              configMapKeyRef:
                name: graylog-master-config
                key: trusted_proxies
          ports:
          - containerPort: 9000
            name: http
          - containerPort: 12201
            name: udp-input
          - containerPort: 1514
            name: tcp-input
          volumeMounts:
          - name: graylog-persistent-storage
            mountPath: /usr/share/graylog/data/journal
            subPath: graylog
          - name: graylog-plugins-storage
            mountPath: /usr/share/graylog/plugin
            subPath: graylog
          resources:
            requests:
              cpu: .25
              memory: 1536Mi
            limits:
              cpu: 1.5
              memory: 2048Mi
          readinessProbe:
            httpGet:
              path: /api/system/lbstatus
              port: 9000
            initialDelaySeconds: 90
            periodSeconds: 3
            timeoutSeconds: 60
            successThreshold: 1
            failureThreshold: 2
        - name: graylog-oidc-proxy-sidecar
          image:  itsre/graylog-oidc-proxy:1.9.6
          env:
          - name: discovery_url
            valueFrom:
              configMapKeyRef:
                name: graylog-oidc-proxy-config
                key: discovery_url
          - name: backend
            valueFrom:
              configMapKeyRef:
                name: graylog-oidc-proxy-config
                key:  backend
          - name: app_name
            valueFrom:
              configMapKeyRef:
                name: graylog-oidc-proxy-config
                key: app_name
          - name: aws_region
            valueFrom:
              configMapKeyRef:
                name: graylog-oidc-proxy-config
                key: aws_region
          - name: host_name
            valueFrom:
              configMapKeyRef:
                name: graylog-oidc-proxy-config
                key: host_name
          - name: oidc_client_id
            valueFrom:
              secretKeyRef:
                name: graylog-oidc-proxy-secret
                key: oidc_client_id
          - name: oidc_client_secret
            valueFrom:
              secretKeyRef:
                name: graylog-oidc-proxy-secret
                key: oidc_client_secret
          - name: oidc_crypto_passphrase
            valueFrom:
              secretKeyRef:
                name: graylog-oidc-proxy-secret
                key: oidc_crypto_passphrase
          ports:
          - containerPort: 8000
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
      securityContext:
        runAsNonRoot: false
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: graylog-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "logging-storage"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 60Gi
  - metadata:
      name: graylog-plugins-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "logging-storage"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: graylog-master-exporter
  name: graylog
  namespace: logging
spec:
  endpoints:
  - interval: 30s
    path: /api/plugins/org.graylog.plugins.metrics.prometheus/metrics
    port: http-app
    scheme: http
    basicAuth:
      username: 
        name: graylog-prometheus-user-credentials
        key: username
      password: 
        name: graylog-prometheus-user-credentials
        key: password
  jobLabel: k8s-graylog-master
  selector:
    matchLabels:
      k8s-app: graylog-master
---
apiVersion: v1
kind: Service
metadata:
  name: graylog-master
  labels:
    name: graylog-master
    k8s-app: graylog-master
  namespace: logging
spec:
  selector:
    k8s-app: graylog-master
  ports:
  - name: http-app
    protocol: TCP
    port: 9000
  - name: http-proxy
    protocol: TCP
    port: 8000
  clusterIP: None

